// Renders README panels from the HTML template and assembles README.md.
// Usage: node scripts/build.mjs   (expects data/stats.json + data/calendar.json)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join } from "node:path";
import puppeteer from "puppeteer";
import { buildHTML } from "../src/template.mjs";
import { buildHeatmap } from "./gen-heatmap.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const P = (rel) => join(root, rel);

const profile = JSON.parse(readFileSync(P("data/profile.json"), "utf8"));
const stats = JSON.parse(readFileSync(P("data/stats.json"), "utf8"));
const heatmap = buildHeatmap();

// --- render HTML to disk (relative asset paths resolve from project root) ---
const html = buildHTML(profile, stats, heatmap);
writeFileSync(P(".render.html"), html);
mkdirSync(P("assets/panels"), { recursive: true });

// which panels are theme-sensitive (need a -dark variant)
const SINGLE = ["stats", "k01", "k02", "k03", "k04"];
const DUAL = ["hero", "cap", "support",
  ...profile.selectedWork.map((w) => `tile-${w.id}`),
  ...profile.inTheForge.map((w) => `tile-${w.id}`)];

const widths = {}; // captured CSS width per element id (for correct display size)
async function shoot(page, id, suffix = "") {
  const el = await page.$(`#${id}`);
  if (!el) { console.warn("missing element:", id); return; }
  const box = await el.boundingBox();
  if (box && !suffix) widths[id] = Math.round(box.width);
  await el.screenshot({ path: P(`assets/panels/${id}${suffix}.png`), omitBackground: true });
}

const browser = await puppeteer.launch({ headless: "new", args: ["--no-sandbox", "--force-device-scale-factor=2"] });
const page = await browser.newPage();
await page.setViewport({ width: 1000, height: 2000, deviceScaleFactor: 2 });
await page.goto(pathToFileURL(P(".render.html")).href, { waitUntil: "networkidle0" });
await page.evaluate(async () => { if (document.fonts) await document.fonts.ready; });

for (const id of [...SINGLE, ...DUAL]) await shoot(page, id);
await page.evaluate(() => document.documentElement.setAttribute("data-theme", "dark"));
await page.evaluate(async () => { if (document.fonts) await document.fonts.ready; });
for (const id of DUAL) await shoot(page, id, "-dark");

await browser.close();
console.log("panels rendered:", SINGLE.length + DUAL.length * 2);

// --- assemble README.md ---
writeFileSync(P("README.md"), assembleReadme(profile, stats));
console.log("README.md written");

function pic(id, w, alt) {
  const width = w || widths[id];
  return `<picture><source media="(prefers-color-scheme: dark)" srcset="assets/panels/${id}-dark.png"><img src="assets/panels/${id}.png"${width ? ` width="${width}"` : ""} alt="${alt}"></picture>`;
}
function img(id, w, alt) {
  const width = w || widths[id];
  return `<img src="assets/panels/${id}.png"${width ? ` width="${width}"` : ""} alt="${alt}">`;
}
function tilesBlock(items) {
  const cards = items
    .map((t) => `<a href="${t.href}">${pic(`tile-${t.id}`, 400, `${t.name} — ${t.desc}`)}</a>`)
    .join("\n");
  return `<p align="left">\n${cards}\n</p>`;
}

function assembleReadme(p, s) {
  const L = p.links;
  const heroAlt = `I'm ${p.name}, building as ${p.brand} (@${p.handle}). ${p.pitch} Links: daftforge.com, email, LinkedIn, Work with me, Book a call.`;
  const statsAlt = `${s.commits.toLocaleString("en-US")} commits, ${s.prs} pull requests, ${s.issues} issues, ${s.repos} repos, MIT licensed. Stack: ${(p.stack || []).join(", ")}. Language split: ${s.languages.map((l) => `${l.name} ${l.pct}%`).join(", ")}. Forge-heat contribution heatmap: ${s.totalContributions.toLocaleString("en-US")} contributions this year.`;
  const capAlt = p.capabilities.map((c) => `${c.title}: ${c.body}`).join(" ");

  return `<!-- This file is generated by scripts/build.mjs.
     Edit content in data/profile.json and layout/style in src/template.mjs, then run \`npm run build\`.
     The GitHub Action refreshes the stats + heatmap on a schedule.
     Layout is table-free on purpose: GitHub styles HTML tables with cell borders,
     which would box the design. Sections are images; interactive parts are inline links. -->

<div align="center">

${pic("hero", 880, heroAlt)}

<a href="${L.workWithMe}"><b>Work with me</b></a> &nbsp;·&nbsp; <a href="${L.bookACall}">Book a call</a> &nbsp;·&nbsp; <a href="${L.website}">daftforge.com</a> &nbsp;·&nbsp; <a href="mailto:${L.email}">Email</a> &nbsp;·&nbsp; <a href="${L.linkedin}">in/james-baker</a>

</div>

${img("stats", 880, statsAlt)}

${img("k01", 0, "// 01 · what I build")}

${pic("cap", 880, capAlt)}

${img("k02", 0, "// 02 · selected work")}

${tilesBlock(p.selectedWork)}

${img("k03", 0, "// 03 · in the forge")}

${tilesBlock(p.inTheForge)}

${img("k04", 0, "// 04 · support the open tools")}

<a href="${L.support}">${pic("support", 880, `${p.support.line} ${p.support.cta}`)}</a>

<div align="center">

<picture><source media="(prefers-color-scheme: dark)" srcset="assets/brand/footer-dark.png"><img src="assets/brand/footer-light.png" width="230" alt="${p.brand}"></picture>

<sub><a href="${L.website}">daftforge.com</a> &nbsp;·&nbsp; <a href="${L.workWithMe}">Work with me</a> &nbsp;·&nbsp; <a href="${L.bookACall}">Book a call</a> &nbsp;·&nbsp; <a href="${L.linkedin}">LinkedIn</a> &nbsp;·&nbsp; <a href="mailto:${L.email}">Email</a> &nbsp;·&nbsp; <a href="${L.github}">GitHub</a></sub>

</div>
`;
}
